# SPDX-License-Identifier: GPL-2.0
# The parent qcom directory builds the Qualcomm base DTBs.
dtb-$(CONFIG_ARCH_CANOE) += infiniti-24831-canoe-overlay.dtbo \
                         infiniti-24863-canoe-overlay.dtbo

always-y := $(dtb-y)
clean-files := *.dtb *.dtbo
